-- MySQL Script generated by MySQL Workbench
-- Fri Jan 25 19:55:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fylke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fylke` (
  `id` INT NOT NULL,
  `navn` VARCHAR(45) NOT NULL,
  `areal` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kommune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kommune` (
  `id` INT NOT NULL,
  `navn` VARCHAR(45) NOT NULL,
  `areal` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kommuner over tid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kommuner_over_tid` (
  `aar` YEAR NOT NULL,
  `fylke_id` INT NOT NULL,
  `kommune_id` INT NOT NULL,
  INDEX `fk_kommuner_over_tid_kommune1_idx` (`kommune_id` ASC),
  CONSTRAINT `fk_kommuner_over_tid_fylke1`
    FOREIGN KEY (`fylke_id`)
    REFERENCES `mydb`.`fylke` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kommuner_over_tid_kommune1`
    FOREIGN KEY (`kommune_id`)
    REFERENCES `mydb`.`kommune` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kommunelandbruksareal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kommunelandbruksareal` (
  `landbruksareal` INT NULL,
  `aar` YEAR NOT NULL,
  `kommune_id` INT NOT NULL,
  CONSTRAINT `fk_kommunelandbruksareal_kommune1`
    FOREIGN KEY (`kommune_id`)
    REFERENCES `mydb`.`kommune` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
