-- MySQL Script generated by MySQL Workbench
-- Fri Jan 25 19:55:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fylke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fylke` (
  `id` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Areal` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kommune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kommune` (
  `id` INT NOT NULL,
  `Navn` VARCHAR(45) NOT NULL,
  `Areal` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kommuner over tid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kommuner over tid` (
  `Aar` YEAR NOT NULL,
  `Fylke_id` INT NOT NULL,
  `Kommune_id` INT NOT NULL,
  INDEX `fk_Kommuner over tid_Kommune1_idx` (`Kommune_id` ASC),
  CONSTRAINT `fk_Kommuner over tid_Fylke1`
    FOREIGN KEY (`Fylke_id`)
    REFERENCES `mydb`.`Fylke` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kommuner over tid_Kommune1`
    FOREIGN KEY (`Kommune_id`)
    REFERENCES `mydb`.`Kommune` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FylkeLandbruksareal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FylkeLandbruksareal` (
  `Landbruksareal` INT(11) NULL,
  `Aar` YEAR NOT NULL,
  `Fylke_id` INT NOT NULL,
  `FylkeLandbruksarealcol` VARCHAR(45) NULL,
  CONSTRAINT `fk_FylkeLandbruksareal_Fylke`
    FOREIGN KEY (`Fylke_id`)
    REFERENCES `mydb`.`Fylke` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KommuneLandbruksareal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KommuneLandbruksareal` (
  `Landbruksareal` INT NULL,
  `Aar` YEAR NOT NULL,
  `Kommune_id` INT NOT NULL,
  CONSTRAINT `fk_KommuneLandbruksareal_Kommune1`
    FOREIGN KEY (`Kommune_id`)
    REFERENCES `mydb`.`Kommune` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
