-- MySQL Script generated by MySQL Workbench
-- to. 02. mai 2019 kl. 15.10 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fylke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fylke` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fylke` (
  `id` INT NOT NULL,
  `navn` VARCHAR(45) NOT NULL,
  `areal` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kommune`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kommune` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kommune` (
  `id` INT NOT NULL,
  `navn` VARCHAR(45) NOT NULL,
  `areal` INT(11) NOT NULL,
  `startaar` INT(11) NOT NULL,
  `sluttaar` INT(11) NOT NULL,
  `fylke_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fylke_id`),
  INDEX `fk_Kommune_fylke1_idx` (`fylke_id` ASC),
  CONSTRAINT `fk_Kommune_fylke1`
    FOREIGN KEY (`fylke_id`)
    REFERENCES `mydb`.`fylke` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KommuneLandbruksareal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kommunelandbruksareal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kommunelandbruksareal` (
  `landbruksareal` INT NULL,
  `aar` YEAR NOT NULL,
  `kommune_id` INT NOT NULL,
  CONSTRAINT `fk_KommuneLandbruksareal_Kommune1`
    fOREIGN KEY (`kommune_id`)
    REFERENCES `mydb`.`kommune` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
